DROP DATABASE IF EXISTS course;
USE course;

DROP TABLE IF EXISTS user;
CREATE TABLE user (
  id INT NOT NULL AUTO_INCREMENT COMMENT '用户编号',
  username VARCHAR(255) NOT NULL COMMENT '用户名',
  password VARCHAR(255) NOT NULL COMMENT '密码',
  realName VARCHAR(255) NOT NULL COMMENT '真实姓名',
  mobile BIGINT(20) NOT NULL COMMENT '手机号',
  email VARCHAR(255) NOT NULL COMMENT '电子邮箱',
  PRIMARY KEY (id)
)  ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='用户信息表';