DROP DATABASE IF EXISTS course;
USE course;

DROP TABLE IF EXISTS user;
CREATE TABLE user (
  id INT NOT NULL AUTO_INCREMENT COMMENT '用户编号',
  username VARCHAR(255) NOT NULL COMMENT '用户名',
  password VARCHAR(255) NOT NULL COMMENT '密码',
  realName VARCHAR(255) NOT NULL COMMENT '真实姓名',
  mobile BIGINT(20) NOT NULL COMMENT '手机号',
  email VARCHAR(255) NOT NULL COMMENT '电子邮箱',
  PRIMARY KEY (id)
)  ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='用户信息表';

DROP TABLE IF EXISTS course;
CREATE TABLE course (
  id INT NOT NULL AUTO_INCREMENT COMMENT '课程编号',
  course_name VARCHAR(255) NOT NULL COMMENT '课程名称',
  description VARCHAR(255) NULL COMMENT '课程描述',
  teacher_id INT NOT NULL COMMENT '教师姓名',
  PRIMARY KEY (id)
)  ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='课程信息表';

DROP TABLE IF EXISTS teacher;
CREATE TABLE teacher (
  id INT NOT NULL AUTO_INCREMENT COMMENT '教师编号',
  teacher_name VARCHAR(255) NOT NULL COMMENT '教师名称',
  score INT NOT NULL DEFAULT 100 COMMENT '教师评分',
  PRIMARY KEY (id)
)  ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='教师信息表';